name: flame_jam_2023
description: "A cold and hot puzzle platformer game. Made with flame"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.12.0
  flame_lint: ^1.1.2
  flame_audio: ^2.1.5
  flame_tiled: ^1.18.1
  flame_svg: ^1.8.7
  flame_riverpod: ^5.1.0
  leap: ^0.5.2
  tiled: ^0.10.1
  flame_behaviors: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/