name: flame_jam_2023
description: "A cold and hot puzzle platformer game. Made with flame"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.11.0
  flame_lint: ^1.1.2
  flame_audio: ^2.1.4
  flame_tiled: ^1.18.0
  flame_svg: ^1.8.6
  flame_riverpod: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true